pages:
  stage: deploy
  tags:
  - shell
  script:
  - echo " => copie dans diapo pour publication sur pages"
  - mkdir .diapo
  - cp -r  * .diapo/
  - mv .diapo diapo
  artifacts:
    paths:
    - diapo
  only:
  - master
